services:
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    volumes:
      - ./frontend:/var/www/html
    networks:
      - caddy_network
    labels:
      caddy: ${REPO_NAME}
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy_network:
    external: false